# Rosé Pine Moon palette.
TMUX_STATUS_BACKGROUND=#2a273f
TMUX_STATUS_PANEL=#393552
TMUX_STATUS_ACTIVE_INDEX_FG=#393552
TMUX_STATUS_ACTIVE_TEXT=#ea9a97
TMUX_STATUS_ACTIVE_CONTEXT_BG=#393552
TMUX_STATUS_INACTIVE_BG=#2a273f
TMUX_STATUS_COPY_SELECTION_BG=#44415a
TMUX_STATUS_MUTED=#908caa
TMUX_STATUS_PRIMARY=#3e8fb0
TMUX_STATUS_ACCENT=#ea9a97
TMUX_STATUS_PREFIX=#9ccfd8
TMUX_STATUS_BELL=#f6c177
TMUX_STATUS_COPY_MODE=#c4a7e7
TMUX_STATUS_SYNC=#eb6f92
TMUX_STATUS_ON_COLOR=#232136
TMUX_STATUS_BAR_FG=#e0def4
TMUX_STATUS_BAR_ACCENT=#ea9a97
TMUX_STATUS_INACTIVE_CONTEXT=#6e6a86
TMUX_STATUS_INACTIVE_INDEX_FG=#393552
TMUX_STATUS_INACTIVE_INDEX_BG=#6e6a86
