# Choose tree bindings

set -g @choose_tree_format '#{?window_bell_flag,#[fg=#e0af68][!] #[default],}#[fg=#{?window_active,#bb9af7,#565f89}]#{?#{@pi_session_active},pi,#{?#{@codex_session_active},codex,#{?#{@ssh_session_active},ssh,#{pane_current_command}}}}#[default] #[fg=#565f89]| #[fg=#{?window_active,#7aa2f7,#565f89}]#{?#{@pi_session_active},#{b:pane_current_path}#{?#{@pi_session_name}, | #{=/98/..:@pi_session_name},},#{?#{@codex_session_active},#{b:pane_current_path}#{?#{@codex_session_name}, | #{=/98/..:@codex_session_name},},#{?#{@ssh_session_active},#{=/98/..:@ssh_session_name},#{b:pane_current_path}}}}#[default]'

bind-key p choose-tree -Z -F '#{E:@choose_tree_format}'
bind-key C-p choose-tree -Z -F '#{E:@choose_tree_format}'
bind-key -n M-p choose-tree -Z -F '#{E:@choose_tree_format}'
