#!/usr/bin/osascript

# AppleScript for create a new space/desktop for MacOS
tell application "System Events"
  do shell script "/System/Applications/Mission\\ Control.app/Contents/MacOS/Mission\\ Control"
  click button 1 of group "Spaces Bar" of group 1 of group "Mission Control" of process "Dock"
  delay 0.6
  do shell script "/System/Applications/Mission\\ Control.app/Contents/MacOS/Mission\\ Control"
end tell
